#!/usr/bin/python3

import sys
import socket
import select
import time
import random
import numpy as np
import math
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import zappy_parsing as zp
import zappy_network_utils as znu

def main():
    args = zp.get_args()
    sock = znu.con_to_server(args)


try:
    main()
except Exception as e:
    print(e)
    exit(84)