name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt-get
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
    - name: compiles raylib
      run: git clone https://github.com/raysan5/raylib.git raylib
    - name: compiles raylib
      run: cd raylib/src && sudo make install
    - name: make
      run: make
