name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check commit author
      run: |
        $AUTHOR=$(git log -1 --pretty=format:'%ae')
        if [ "$AUTHOR" = "frederic.lechevalier@epitech.eu" ]; then
          echo "les problèmes"
          git reset --hard HEAD~1
          git push --force
          exit 1
        fi
